kind = "web"
previewPath = "/"
title = "NITROVIA"
version = "1.0.0"
id = "artifacts/nitrovia"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 20924

[services.development]
run = "pnpm --filter @workspace/nitrovia run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/nitrovia", "run", "build" ]
serve = "static"
publicDir = "artifacts/nitrovia/dist/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "20924"
BASE_PATH = "/"
